### PR TITLE
(#40) Explicit db config

### PR DESCRIPTION
**Pull request by fleischie**
Make the database file configuration explicit, by allowing a new configuration item `DB_FILE_MAIN` - which defaults to `''` - to define the path to store the database file as.

This PR has the following features:
- Set the `DB_FILE_MAIN` configuration item via a `config --database-path` call. Unset the item by not giving a path to the previous mentioned config call.
- Validate and normalize the given configuration value to be available before storing it in the config.
- Fallback to the default `~/.moro-data.db` path, if configuration is unset.
- Explicitly use the test database for testing in a cross-OS manner. This way the `removeDatabase` function does not need to have the database file path passed in.

This is targeted to be backwards-compatible. If there is anythin I forgot to address or anything, that is not the way it should be, I can always update the PR. Just drop me a line here. :slightly_smiling_face:

### CODE REVIEW

**Comment by omidfi** [comment]
Wow this is awesome! I wish all pull requests were well documented like this :) 

Here are some minor things I saw:
  * moro config --db  is mentioned in the example in help, but gives  Error: Unknown option --db. Did you mean --day ?

**Comment by fleischie** [comment]
No, haha. I started with this PR, before you mentioned your plans in #40 . Thus the original option-flag was simply called `--db` and not `--database-path`. :stuck_out_tongue_winking_eye: 

I must have forgotten to update the help text in the `constants.json`. :slightly_smiling_face:

I can update the PR with an additional mention in the README, if you think this is ok.

**Comment by omidfi** [comment]
@fleischie Cool. Yes please update it.  

Now that you're fixing that please also updatet the example to have an absolute path, so instead of ./moro.db, change it to something like /home/GraceHopper/.moro.db

**Comment by omidfi** [comment]
This is perfect. I'll go ahead and merge it, we'll fix the help later :)

**Pull request merged**
