### PR TITLE
Refactoring & Date Pattern

### PR DESCRIPTION
**Pull request by mario-s**
Moved the calculate work hours method to the helpers & changed the return object. So that the report could also create a sum row per week.

It is also possible to configure the date pattern.

### CODE REVIEW

**Comment by omidfi** [comment]
Thanks @mario-s I highly appreciate it. 
Could you help with resolving the merge conflicts? I couldn't figure it out. Seems like you have worked at the top of your old fork.

**Comment by omidfi** [comment]
This is how I resolved the conflicts: https://github.com/omidfi/moro/pull/37

How does it look to you?

**Comment by mario-s** [comment]
Yeah, looks good to me. Sorry that you had this trouble with merging. I'll see how I can avoid so many conflicts

**Comment by omidfi** [comment]
@mario-s no problem :)   
You just need to update your fork before working on it. Or just fork again for each pull request.

**Comment by omidfi** [comment]
@mario-s I just published the new release. You can update and see your changes :)

**Pull request closed without merging**
