### PR TITLE
new full report

### PR DESCRIPTION
**Pull request by mario-s**
The table for the full report has now a header, a week column and a sum row. The sum will be added if the week changes and the number of records for the old week is higher than one. Also at the end if there is more than one record in the current week.

Please review and close the issue if satisfied.

### CODE REVIEW

**Comment by omidfi** [comment]
Awesome I'll check it this weekend latest :)

**Comment by omidfi** [comment]
thanks a lot @mario-s :) 

I'll release it a bit later.

**Comment by omidfi** [comment]
@mario-s moro 2.9.0 is published! 
Please note that I made a small change. The report --all looked a bit complicated, with showing week number beside each day. So I removed the week numbers, and only kept the sum rows. I hope it fits your design well :)

**Comment by mario-s** [comment]
@omidfi Yeah of course I'm fine with that. I thought it might be useful in a case when you have only one entry for the previous week and several for the current week (A sum row will be only added when there are more then one entry in a week). Then the sum row might be misunderstood by the user and say that this is not the sum over all. 

Anyway let's see what people think about it.

**Comment by omidfi** [comment]
@mario-s  yeah, I understand your concern.  Wouldn't it make sense to add sum rows to every week? Even with only one row?

**Comment by mario-s** [comment]
@omidfi Ok. Looks a bit cluttered then, but would be fine for me.

**Comment by mario-s** [comment]
@omidfi The condition for the dayCounter variable needs to be adjusted. Would you complete this task?

**Comment by omidfi** [comment]
@mario-s I tried but I got wrong sums in the report :(  
I can check again later. Would be nice if you could fix it but I understand if you don't have time.

**Comment by omidfi** [comment]
@mario-s no worries, it's fixed now :)

**Comment by mario-s** [comment]
@omidfi I also just did it. But my outcome differs from your's. Choose the one that fits;-)

**Comment by omidfi** [comment]
Huh huh :) I merged both and seems like everything is good @mario-s

**Comment by omidfi** [comment]
Ok published. Thanks @mario-s :)

**Pull request merged**
